//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitap2
    {
        public int id { get; set; }
        public string ad { get; set; }
        public Nullable<int> yazarno { get; set; }
        public Nullable<int> sayi { get; set; }
    
        public virtual yazar yazar { get; set; }
    }
}
