//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyon
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphaneyeniEntities1 : DbContext
    {
        public kutuphaneyeniEntities1()
            : base("name=kutuphaneyeniEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<islem> islem { get; set; }
        public virtual DbSet<kitap> kitap { get; set; }
        public virtual DbSet<ogrenci> ogrenci { get; set; }
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tur> tur { get; set; }
        public virtual DbSet<uyeler> uyeler { get; set; }
        public virtual DbSet<yazar> yazar { get; set; }
        public virtual DbSet<anonimkitaplar> anonimkitaplar { get; set; }
        public virtual DbSet<kitap2> kitap2 { get; set; }
        public virtual DbSet<siniflar> siniflar { get; set; }
    }
}
